version: 2
jobs:
  code-quality-and-unit-tests:
    docker:
      # Stretch
      - image: circleci/php:7.2-apache-node-browsers-legacy
      - image: circleci/mariadb:latest
        environment:
          - MYSQL_ROOT_PASSWORD=circleci
          - WP2STATIC_E2E_TEST_URL="http://127.0.0.1"
          - WP2STATIC_E2E_TEST_USER=admin
          - WP2STATIC_E2E_TEST_PASS=banana

    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            echo "memory_limit = 512M" | sudo -E tee --append /usr/local/etc/php/conf.d/docker-php-memory.ini
            sudo apt install -y mariadb-client wget curl
            sudo docker-php-ext-install mysqli
      - run:
          name: Install node modules
          command: |
            npm install
      - run:
          name: Install PHP packages via Composer
          command: |
            composer install --quiet
      - run:
          name: Run code quality and functionality tests
          command: |
            composer test
      - run:
          name: Setup Apache site
          command: |
            sudo cp /home/circleci/project/.circleci/apache.conf /etc/apache2/sites-available/wp2static.conf
            sudo a2ensite wp2static.conf
            sudo service apache2 restart
      - run:
          name: Create DB for WordPress
          command: |
            mysql -u root -pcircleci -h 127.0.0.1 -e "create database wordpress"

      - run:
          name: Install WP-CLI
          command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar

      - run:
          name: Download WP
          command: |
            ./wp-cli.phar core download --allow-root --path=wordpress

      - run:
          name: Create wp-config.php
          command: |
            ./wp-cli.phar config create --allow-root --dbname=wordpress --dbuser=root --dbpass=circleci --dbhost=127.0.0.1 --path=wordpress

      - run:
          name: Install WordPress
          command: |
            ./wp-cli.phar core install --allow-root --admin_user=admin --admin_password=banana --admin_email=admin@example.com --url=http://127.0.0.1 --title=WP2StaticCircleCI --path=wordpress

      - run:
          name: Build WP2Static zip
          command: |
            composer build wp2staticCIBuild uncompressed
      - run:
          name: Install and activate WP2Static
          command: |
              ./wp-cli.phar --debug plugin install --activate $HOME/Downloads/wp2staticCIBuild.zip --path=wordpress
      - run:
          name: install dependencies for Jest
          command: |
            sudo npm i -g jest
      - run:
          name: run E2E tests
          command: |
            jest

workflows:
  version: 2
  workflow-code-quality-and-unit-tests:
    jobs:
      - code-quality-and-unit-tests
