version: 2
jobs:
  code-quality-and-unit-tests:
    docker:
      - image: circleci/php:7.2-apache-node-browsers-legacy
    steps:
      - checkout
      - run:
        name: Dependencies
        command: |
          echo "memory_limit = 512M" | sudo -E tee --append /usr/local/etc/php/conf.d/docker-php-memory.ini
      - run:
          name: Install node modules
          command: |
            npm install
      - run:
          name: Run code quality checks
          command: |
            composer install --quiet
            composer test

workflows:
  version: 2
  workflow-code-quality-and-unit-tests:
    jobs:
      - code-quality-and-unit-tests
