version: 2
jobs:
  build:
    docker: 
      - image: circleci/php:7.2.8-apache-node
    steps:
      - checkout
      - run: 
          name: Run Code Sniffs
          command: phpcs library/StaticHTMLOutput.php
      - run: 
          name: Run Unit Tests
          command: ./provisioning/run_unit_tests.sh
