version: 2
jobs:
  code-quality-and-unit-tests:
    docker:
      - image: circleci/php:7.2-apache-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: install-npm-packages
          command: 'npm i'
      - run:
          name: Run code quality checks
          command: |
            composer install --quiet
            composer test

workflows:
  version: 2
  workflow-code-quality-and-unit-tests:
    jobs:
      - code-quality-and-unit-tests
