version: 2
jobs:
  code-quality-and-unit-tests:
    docker:
      # Stretch
      - image: circleci/php:7.2-apache-node-browsers-legacy
      - image: circleci/mariadb:latest
        environment:
          - MYSQL_ROOT_PASSWORD=circleci
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            echo "memory_limit = 512M" | sudo -E tee --append /usr/local/etc/php/conf.d/docker-php-memory.ini
            sudo apt install -y mariadb-client wget curl
            sudo docker-php-ext-install mysqli
      - run:
          name: Install node modules
          command: |
            npm install
      - run:
          name: Run code quality checks
          command: |
            composer install --quiet
            composer test
      - run:
          name: setup WordPress site for E2E tests
          command: |
            pwd # /home/circleci/project/

            sudo cp /home/circleci/project/.circleci/apache.conf /etc/apache2/sites-available/wp2static.conf
            sudo a2ensite wp2static.conf
            sudo service apache2 restart

            mysql -u root -pcircleci -h 127.0.0.1 -e "create database wordpress"

            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar

            ./wp-cli.phar core download --allow-root --path=wordpress

            ./wp-cli.phar config create --debug --allow-root --dbname=wordpress --dbuser=root --dbpass=circleci --dbhost=127.0.0.1 --path=wordpress

            cat /home/circleci/project/wordpress/wp-config.php

            ./wp-cli.phar core install --debug --allow-root --admin_name=admin --admin_password=admin --admin_email=admin@example.com --url=http://127.0.0.1 --title=WP2StaticCircleCI --path=wordpress

            # copy project files to plugin dir (TODO: build to zip and install)
            cp -r $CIRCLE_WORKING_DIRECTORY wordpress/wp-content/plugins/static-html-output-plugin

            ./wp-cli.phar plugin activate static-html-output-plugin --path=wordpress
      - run:
        name: install dependencies for Jest
        command: |
          sudo npm i -g jest
      - run:
        name: run E2E tests
        command: |
          jest

workflows:
  version: 2
  workflow-code-quality-and-unit-tests:
    jobs:
      - code-quality-and-unit-tests
