name: codequality

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]

    name: PHP-${{ matrix.php }} 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Validate Composer setup
      run: composer validate --strict

    - name: Install PHP dependencies
      run: composer install --no-interaction

    - name: Run parallel lint
      run: composer run-script lint

    - name: Test PHP Coding Standards
      run: composer run-script phpcs

    - name: Test code against PHP 7.4 standard
      run: composer run-script php74

    - name: Test code against PHP 8.0 standard
      run: composer run-script php80

    - name: Test code against PHP 8.1 standard
      run: composer run-script php81

    - name: Run PHPStan static analyser
      run: composer run-script phpstan

    - name: Run unit tests, ignoring external requests
      run: composer run-script phpunit -- --exclude-group ExternalRequests

